---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: database-config
  labels:
    app: database
    application: coolstore-service
data:
  POSTGRESQL_DATABASE: ZGI=
  POSTGRESQL_USERNAME: dXNlcg==
  POSTGRESQL_PASSWORD: c3VwZXJTZWNyZXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
    application: coolstore-service
    app.kubernetes.io/part-of: coolstore
    app.openshift.io/runtime: postgresql
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      name: database
  template:
    metadata:
      labels:
        application: coolstore-service
        name: database
    spec:
      containers:
        - image: bitnami/postgresql:13
          name: database
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: database-config
          volumeMounts:
            - name: database-data
              mountPath: /bitnami/postgresql
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 32Mi
      volumes:
        - name: database-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: database
    application: coolstore-service
  name: database
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: database
  type: ClusterIP